


const booksData = [
    { id: 1, title: 'Book Title 1', author: 'Author 1', rating: '4.5', description: 'This comprehensive guide explores the fundamental principles of physics. It covers topics from classical mechanics to quantum theory. Perfect for students and enthusiasts alike, it simplifies complex concepts.', pdf: "../assets/cover.pdf", image: "/assets/bookimg/web.jpg"},
    { id: 2, title: 'Book Title 2', author: 'Author 2', description: 'This comprehensive guide explores the fundamental principles of physics. It covers topics from classical mechanics to quantum theory. Perfect for students and enthusiasts alike, it simplifies complex concepts.', pdf: 'https://pdfdrive.com.co/cracking-codes-with-python/' },
    { id: 3, title: 'Book Title 3', author: 'Author 3', description: 'This comprehensive guide explores the fundamental principles of physics. It covers topics from classical mechanics to quantum theory. Perfect for students and enthusiasts alike, it simplifies complex concepts.', pdf: 'https://pdfdrive.com.co/cracking-codes-with-python/' },
    { id: 4, title: 'Book Title 4', author: 'Author 4', description: 'This comprehensive guide explores the fundamental principles of physics. It covers topics from classical mechanics to quantum theory. Perfect for students and enthusiasts alike, it simplifies complex concepts.', pdf: 'https://pdfdrive.com.co/cracking-codes-with-python/' },
    { id: 5, title: 'Book Title 5', author: 'Author 5', description: 'This comprehensive guide explores the fundamental principles of physics. It covers topics from classical mechanics to quantum theory. Perfect for students and enthusiasts alike, it simplifies complex concepts.', pdf: 'https://pdfdrive.com.co/cracking-codes-with-python/' },
    { id: 6, title: 'Book Title 6', author: 'Author 6', description: 'This comprehensive guide explores the fundamental principles of physics. It covers topics from classical mechanics to quantum theory. Perfect for students and enthusiasts alike, it simplifies complex concepts.', pdf: 'https://pdfdrive.com.co/cracking-codes-with-python/' },
    { id: 7, title: 'Book Title 7', author: 'Author 7', description: 'This comprehensive guide explores the fundamental principles of physics. It covers topics from classical mechanics to quantum theory. Perfect for students and enthusiasts alike, it simplifies complex concepts.', pdf: 'https://pdfdrive.com.co/cracking-codes-with-python/' },
    { id: 8, title: 'Book Title 8', author: 'Author 8', description: 'This comprehensive guide explores the fundamental principles of physics. It covers topics from classical mechanics to quantum theory. Perfect for students and enthusiasts alike, it simplifies complex concepts.', pdf: 'https://pdfdrive.com.co/cracking-codes-with-python/' },
    { id: 9, title: 'Book Title 9', author: 'Author 9', description: 'This comprehensive guide explores the fundamental principles of physics. It covers topics from classical mechanics to quantum theory. Perfect for students and enthusiasts alike, it simplifies complex concepts.', pdf: 'https://pdfdrive.com.co/cracking-codes-with-python/' },
    { id: 10, title: 'Book Title 10', author: 'Author 10', description: 'This comprehensive guide explores the fundamental principles of physics. It covers topics from classical mechanics to quantum theory. Perfect for students and enthusiasts alike, it simplifies complex concepts.', pdf: 'https://pdfdrive.com.co/cracking-codes-with-python/' },
];
export default booksData;