


const booksData = [
    { id: 1, title: 'Data Structure', author: 'Author 1', description: 'This comprehensive guide explores the fundamental principles of physics. It covers topics from classical mechanics to quantum theory. Perfect for students and enthusiasts alike, it simplifies complex concepts.', pdf: "../assets/cover.pdf", image: "/assets/bookimg/1.jpg"},
    { id: 2, title: 'Cyber Security', author: 'Author 2', description: 'This comprehensive guide explores the fundamental principles of physics. It covers topics from classical mechanics to quantum theory. Perfect for students and enthusiasts alike, it simplifies complex concepts.', pdf: 'https://pdfdrive.com.co/cracking-codes-with-python/', image: "/assets/bookimg/2.jpg"},
    { id: 3, title: 'DBMS', author: 'Author 3', description: 'This comprehensive guide explores the fundamental principles of physics. It covers topics from classical mechanics to quantum theory. Perfect for students and enthusiasts alike, it simplifies complex concepts.', pdf: 'https://pdfdrive.com.co/cracking-codes-with-python/', image: "/assets/bookimg/3.jpg" },
    { id: 4, title: 'Web Dev', author: 'Author 4', description: 'This comprehensive guide explores the fundamental principles of physics. It covers topics from classical mechanics to quantum theory. Perfect for students and enthusiasts alike, it simplifies complex concepts.', pdf: 'https://pdfdrive.com.co/cracking-codes-with-python/' , image: "/assets/bookimg/4.jpg"},
    { id: 5, title: 'Internet Technology', author: 'Author 5', description: 'This comprehensive guide explores the fundamental principles of physics. It covers topics from classical mechanics to quantum theory. Perfect for students and enthusiasts alike, it simplifies complex concepts.', pdf: 'https://pdfdrive.com.co/cracking-codes-with-python/', image: "/assets/bookimg/5.jpg" },
    { id: 6, title: 'Java Programming', author: 'Author 6', description: 'This comprehensive guide explores the fundamental principles of physics. It covers topics from classical mechanics to quantum theory. Perfect for students and enthusiasts alike, it simplifies complex concepts.', pdf: 'https://pdfdrive.com.co/cracking-codes-with-python/', image: "/assets/bookimg/6.jpg" },
    { id: 7, title: 'Numerical Methods', author: 'Author 7', description: 'This comprehensive guide explores the fundamental principles of physics. It covers topics from classical mechanics to quantum theory. Perfect for students and enthusiasts alike, it simplifies complex concepts.', pdf: 'https://pdfdrive.com.co/cracking-codes-with-python/' , image: "/assets/bookimg/7.jpg"},
    { id: 8, title: 'PHP', author: 'Author 8', description: 'This comprehensive guide explores the fundamental principles of physics. It covers topics from classical mechanics to quantum theory. Perfect for students and enthusiasts alike, it simplifies complex concepts.', pdf: 'https://pdfdrive.com.co/cracking-codes-with-python/', image: "/assets/bookimg/8.jpg" },
    { id: 9, title: 'Python Programming', author: 'Author 9', description: 'This comprehensive guide explores the fundamental principles of physics. It covers topics from classical mechanics to quantum theory. Perfect for students and enthusiasts alike, it simplifies complex concepts.', pdf: 'https://pdfdrive.com.co/cracking-codes-with-python/' , image: "/assets/bookimg/9.jpg"},
    { id: 10, title: 'UNIX', author: 'Author 10', description: 'This comprehensive guide explores the fundamental principles of physics. It covers topics from classical mechanics to quantum theory. Perfect for students and enthusiasts alike, it simplifies complex concepts.', pdf: 'https://pdfdrive.com.co/cracking-codes-with-python/', image: "/assets/bookimg/10.jpg" },
];
export default booksData;